api/urls.py
from django.urls import path, include
from rest_framework.routers import DefaultRouter
from rest_framework_simplejwt.views import (
    TokenObtainPairView,
    TokenRefreshView,
)

from .views import (
    # AllApiRoute,
    CreateUserApi,
    UserViewSet,

    ##post
    PostViewSet,
    CommentViewSet,
)

router = DefaultRouter()
router.register(r'posts', PostViewSet)
router.register(r'users', UserViewSet)
router.register(r'comments', CommentViewSet )


app_name = 'api'
urlpatterns = [
    # path('', AllApiRoute.as_view(), name='home'),
    path('register/', CreateUserApi.as_view(), name='register'),
    path('token/', TokenObtainPairView.as_view(), name='token_obtain_pair'),
    path('token/refresh/', TokenRefreshView.as_view(), name='token_refresh'),

    path('', include(router.urls)),
]

dj4e/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('api/', include('api.urls')),
    path('', include('post.urls')),
    path('chat/', include('chat.urls')),
    path('api-auth/', include('rest_framework.urls')),
    ### quizes urls
    path('quiz/', include('quizes.urls', namespace='quiz')),
]

post/urls.py
from django.conf import settings
from django.conf.urls.static import static


from django.urls import path
from post.views import (
    PostListView,
    PostCreateView,
    PostDetailView,
    PostUpdateView,
    PostDeleteView,
    LikePostView,
    UnLikePostView,
    #comment
    PostComment,
    DeleteComment,
    LikeCommentView,
    UnLikeCommentView,
    
)
app_name='post'
urlpatterns = [
    
    path('', PostListView.as_view(), name="post"),
    path('create/', PostCreateView.as_view(), name="create"),
    path('detail/<str:pk>/', PostDetailView.as_view(), name="detail"),
    path('update/<str:pk>/', PostUpdateView.as_view(), name="update"),
    path('delete/<str:pk>/', PostDeleteView.as_view(), name="delete"),

    ##likes
    path('like/', LikePostView.as_view(), name='like'),
    path('unlike/', UnLikePostView.as_view(), name='unlike'),

    ##comment
    path('post-comment/', PostComment.as_view(), name="comment"),
    path('delete-comment/<str:pk>/', DeleteComment.as_view(), name="delete_comment"),
    path('like-comment/', LikeCommentView.as_view(), name='like_comment'),
    path('unlike-comment/', UnLikeCommentView.as_view(), name='unlike_comment'),

]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/base.html
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <meta http-equiv="X-UA-Compatible" content="ie=edge" />
    <title>SocialApp</title>
  </head>
  <body>
    <nav style="margin-bottom: 50px;">
      <h2 style="margin: 0;"><a href="{% url 'post:post' %}">SocialApp</a></h2>
      <ul
        style="display: inline-flex; list-style: none; float: right; margin: 0;"
      >
        <form action=".">
          <input type="search" name="qs" placeholder="#tags comming soon" />
          <input type="submit" value="search" />
        </form>
        {% if request.user.is_authenticated %}
        <li><a href="">Friends</a></li>
        <li>
          <a href="{% url 'logout' %}">Logout</a>
        </li>
        {% else%}
        <li>
          <a href="{% url 'login' %}">login</a>
        </li>
        <li>
          <a href="{% url 'register' %}">Register</a>
        </li>
        {% endif %}
      </ul>
    </nav>
    {% block content %} {% endblock %}
  </body>
</html>

templates/baseq.html
{% load static %}
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <meta http-equiv="X-UA-Compatible" content="ie=edge" />
    <link
      rel="stylesheet"
      href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css"
      integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3"
      crossorigin="anonymous"
    />
    <script src="https://code.jquery.com/jquery-3.5.1.min.js"></script>
    <link rel="stylesheet" href="{% static 'style.css' %}" />
    {% block scripts %} {% endblock scripts %}

    <title>quize app| {%block title%} {% endblock title %}</title>
  </head>
  <body>
    <div class="container mt-3">
      {% block content %} {% endblock content %}
    </div>
    <script
      src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"
      integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p"
      crossorigin="anonymous"
    ></script>
    <script
      src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.min.js"
      integrity="sha384-QJHtvGhmr9XOIpI6YVutG+2QOK9T+ZnN4kzFN1RtK3zEFEIsxhlmWl5/YESvpZ13"
      crossorigin="anonymous"
    ></script>
  </body>
</html>