api/urls.py
from django.urls import path, include
from rest_framework.routers import DefaultRouter
from rest_framework_simplejwt.views import (
    TokenObtainPairView,
    TokenRefreshView,
)

from .views import (
    # AllApiRoute,
    CreateUserApi,
    UserViewSet,

    ##post
    PostViewSet,
    CommentViewSet,
)

router = DefaultRouter()
router.register(r'posts', PostViewSet)
router.register(r'users', UserViewSet)
router.register(r'comments', CommentViewSet )


app_name = 'api'
urlpatterns = [
    # path('', AllApiRoute.as_view(), name='home'),
    path('register/', CreateUserApi.as_view(), name='register'),
    path('token/', TokenObtainPairView.as_view(), name='token_obtain_pair'),
    path('token/refresh/', TokenRefreshView.as_view(), name='token_refresh'),

    path('', include(router.urls)),
]

dj4e/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('api/', include('api.urls')),
    path('', include('post.urls')),
    path('chat/', include('chat.urls')),
    path('api-auth/', include('rest_framework.urls')),
    ### quizes urls
    path('quiz/', include('quizes.urls', namespace='quiz')),
]

post/urls.py
from django.conf import settings
from django.conf.urls.static import static


from django.urls import path
from post.views import (
    PostListView,
    PostCreateView,
    PostDetailView,
    PostUpdateView,
    PostDeleteView,
    LikePostView,
    UnLikePostView,
    #comment
    PostComment,
    DeleteComment,
    LikeCommentView,
    UnLikeCommentView,
    
)
app_name='post'
urlpatterns = [
    
    path('', PostListView.as_view(), name="post"),
    path('create/', PostCreateView.as_view(), name="create"),
    path('detail/<str:pk>/', PostDetailView.as_view(), name="detail"),
    path('update/<str:pk>/', PostUpdateView.as_view(), name="update"),
    path('delete/<str:pk>/', PostDeleteView.as_view(), name="delete"),

    ##likes
    path('like/', LikePostView.as_view(), name='like'),
    path('unlike/', UnLikePostView.as_view(), name='unlike'),

    ##comment
    path('post-comment/', PostComment.as_view(), name="comment"),
    path('delete-comment/<str:pk>/', DeleteComment.as_view(), name="delete_comment"),
    path('like-comment/', LikeCommentView.as_view(), name='like_comment'),
    path('unlike-comment/', UnLikeCommentView.as_view(), name='unlike_comment'),

]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

post/models.py
from django.db import models
from accounts.models import User
from django.urls import reverse_lazy
from django.db.models.signals import post_save
from django.dispatch import receiver

# Create your models here.

class Post(models.Model):
    owner = models.ForeignKey(User, on_delete=models.CASCADE)
    title = models.CharField(max_length=170)
    body = models.TextField()
    #tag = models.ManyToManyField(Post, through='PostTag')
    image = models.ImageField(blank=True, null=True, upload_to='post')
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    is_deleted = models.BooleanField(default=False)

    def get_absolute_url(self):
        return reverse_lazy('post:post')
    
    class Meta:
        ordering = ['-created_at']
class Like(models.Model):
    post = models.OneToOneField(Post, on_delete=models.CASCADE)
    liker = models.ManyToManyField(User, related_name='liker')
    liked_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.post.title


class Comment(models.Model):
    body = models.TextField()
    post = models.ForeignKey(Post, related_name='comment',  on_delete=models.CASCADE)
    comment_user = models.ForeignKey(User, on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)
    is_deleted = models.BooleanField(default=False)

    def __str__(self):
        return self.comment_user.username

class CommentLike(models.Model):
    comment = models.OneToOneField(Comment,  on_delete=models.CASCADE)
    comment_liker = models.ManyToManyField(User)
    commented_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return  self.comment.post.title


##Not yet implemented
class CommentReply(models.Model):
    body = models.CharField(max_length=200, blank=True, null=True)
    comment = models.ForeignKey(Comment, on_delete=models.CASCADE)
    reply_user = models.ForeignKey(User, on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)
    is_deleted = models.BooleanField(default=False)

    def __str__(self):
        return self.comment_user

##not yet implemented
# class PostTag(models.Model):
      #title = models..CharField(max_length=48)  
#     post = models.ManyToManyField(Post, related_name='#tag')


###signals
@receiver(post_save, sender=Post)
def my_signal(sender, instance, created, *args, **kwargs):
    
    print(instance.title)
    

post/forms.py
from django.forms import ModelForm
from post.models import Comment


class CommentForm(ModelForm):
    class Meta:
        model = Comment
        fields = ['body']

post/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse_lazy, reverse
from django.shortcuts import get_object_or_404
from django.db.models import Q
from django.views import View
from django.views.generic import ( 
    ListView, 
    CreateView,
    DetailView,
    UpdateView,
    DeleteView
    )
from accounts.models import User
from post.models import Post, Like, Comment, CommentLike
from post.forms import CommentForm

class OwnerCreateView(LoginRequiredMixin, CreateView):
    def form_valid(self, form):
        form.instance.owner = self.request.user
        return super(OwnerCreateView, self).form_valid(form)
class OwnerUpdateView(LoginRequiredMixin, UpdateView):
    def get_queryset(self):
        qs = super().get_queryset()
        return qs.filter(owner=self.request.user)


class PostListView(View):
    def get(self, request):
        query = request.GET.get('qs')
        if query:
            qs = Post.objects.filter(Q(title__icontains=query) |
            Q(body__icontains=query))

            context = {
                'object_list': qs
            }
            return render(request, 'post/post_list.html', context)

        posts = Post.objects.all()
        context = {
            'object_list':posts
        }
        return render(request, 'post/post_list.html', context)

       
        
class PostCreateView(OwnerCreateView):
    model = Post
    fields = ['title', 'body', 'image']

class PostDetailView(DetailView):
    model = Post
    def get(self, request, pk, **kwargs):
        post = Post.objects.get(id=pk)
        comments = Comment.objects.filter(post=pk)
        comment_form =  CommentForm()
        context = {
            'post':post,
            'comments':comments,
            'comment_form':comment_form
        }
        return render(request, 'post/post_detail.html', context)

class PostUpdateView(OwnerUpdateView):
    model = Post
    fields = ['title', 'body', 'image']

class PostDeleteView(DeleteView):
    model = Post
    success_url = reverse_lazy('post:post')
    def get_queryset(self):
        qs = super().get_queryset()
        return qs.filter(owner=self.request.user)


class LikePostView(LoginRequiredMixin, View):
    def post(self, request):
        post_id = request.POST['post_id']
        post = get_object_or_404(Post, id=post_id)
        user = get_object_or_404(User, id=request.user.id)
        obj, created = Like.objects.get_or_create(post=post)
        obj.liker.add(user)
        return redirect(reverse_lazy('post:post'))

class UnLikePostView(LoginRequiredMixin, View):
    def post(self, request):
        post_id = request.POST['post_id']
        post = get_object_or_404(Post, id=post_id)
        user = get_object_or_404(User, id=request.user.id)
        Like.objects.filter(post=post, liker=user).delete()
        
        return redirect(reverse_lazy('post:post'))

##Comment section
class PostComment(LoginRequiredMixin, View):
    def post(self, request):
        post_id = request.POST['post_id']
        post = get_object_or_404(Post, id=post_id)
        comment_form = CommentForm(request.POST)
        if comment_form.is_valid():
            form = comment_form.save(commit=False)
            form.post = post
            form.comment_user = request.user
            form.save()
        return redirect(reverse_lazy('post:detail', args=[post_id]))


class DeleteComment(DeleteView):
    def post(self, request, pk):
        post_id = request.POST['post_id']
        Comment.objects.get(id=pk, comment_user=request.user).delete()
        return redirect(reverse('post:detail', args=[post_id]))

class LikeCommentView(LoginRequiredMixin, View):
    def post(self, request):
        post_id = request.POST['post_id']
        comment_id = request.POST['comment_id']
        comment = get_object_or_404(Comment, id=comment_id)
        user = get_object_or_404(User, id=request.user.id)
        obj, created = CommentLike.objects.get_or_create(comment=comment)
        obj.commenter.add(user)
        return redirect(reverse_lazy('post:detail', args=[post_id]))

class UnLikeCommentView(LoginRequiredMixin, View):
    def post(self, request):
        post_id = request.POST['post_id']
        comment_id = request.POST['comment_id']
        comment = get_object_or_404(Comment, id=comment_id)
        user = get_object_or_404(User, id=request.user.id)
        CommentLike.objects.filter(comment=comment, commenter=user).delete()
        
        return redirect(reverse('post:detail', args=[post_id]))

templates/post/post_confirm_delete.html
{% extends 'base.html' %} {% block content %}
<div>
  <p>Are you sure you want to delete this post {{object.title}}</p>
  <form method="POST">
    {% csrf_token %}
    <input type="submit" value="confirm" />
  </form>
  <a href="{% url 'post:detail' object.id %}">Cancel</a>
</div>
{% endblock %}

templates/post/post_detail.html
{% extends 'base.html' %} {% block content %}
<span></span>
{% load static %} {% load humanize %}
<div>
  {% if request.user == post.owner%}
  <a href="{%url 'post:update' post.id %}">Update Post</a>
  {% endif %}

  <div>
    <a href="{% url 'post:post' %}">Go To Post</a>
  </div>
  <h3>Detail page</h3>
  <h4>{{post.title}}</h4>
  {% if post.image %}
  <img
    style="width: 200px; display: flex; float: right;"
    src="{{ post.image.url }}"
  />
  <br clear="all" />
  {% endif %}
  <p>{{post.body }}</p>
  <p>Posted {{post.created_at|naturaltime}}</p>
  <p>It has {{post.like_set.all|length}} likes</p>
  {% if request.user == post.owner%}
  <a href="{%url 'post:delete' post.id %}">Delete Post</a>
  {% endif %}
  <hr />
  <div>
    Post Comments
    <div>
      {% for comment in comments %}
      <small
        >Commented by
        <a href="{% url 'profile' comment.comment_user.id %}">
          {{comment.comment_user.username}}
        </a>
        by {{comment.created_at|naturaltime}}</small
      >
      <span>{{comment.body}}</span>
      <p>It has {{comment.commentlike.comment_liker.all|length}} likes</p>
      <div>
        {% if request.user.is_authenticated %}
        <small style="display:inline-flex ;">
          <form action="{% url 'post:like_comment' %}" method="POST">
            {% csrf_token %}
            <input type="submit" value="like" />
            <input type="hidden" name="post_id" value="{{post.id}}" />
            <input type="hidden" name="comment_id" value="{{comment.id}}" />
          </form>

          <form action="{% url 'post:unlike_comment' %}" method="POST">
            {% csrf_token %}
            <input type="submit" value="unlike" />
            <input type="hidden" name="post_id" value="{{post.id}}" />
            <input type="hidden" name="comment_id" value="{{comment.id}}" />
          </form>
        </small>
        {% endif %}
      </div>
      <div>
        {% if request.user == comment.comment_user%}
        <form
          action="{% url 'post:delete_comment' comment.id %} "
          method="POST"
        >
          {% csrf_token %}
          <input type="hidden" name="post_id" value="{{post.id}}" />
          <input type="submit" value="Delete" />
        </form>
        {% endif %}
      </div>
      <br />
      {% endfor %}
    </div>
    {% if request.user.is_authenticated %}
    <div>
      <form action="{% url 'post:comment' %}" method="POST">
        {% csrf_token %}
        <input type="hidden" name="post_id" value="{{post.id}}" />
        {{ comment_form.as_p }}
        <input type="submit" value="Comment" />
      </form>
    </div>
    {% endif %}
  </div>
</div>
{% endblock %}

templates/post/post_form.html
{% extends 'base.html' %} {% block content %}
<div>
  <h2>Create a post</h2>
  <div>
    <form method="post" enctype="multipart/form-data">
      {% csrf_token %} {{ form.as_p }}
      <input type="submit" value="Post" />
    </form>
    <a href="{% url 'post:post' %}">Cancel</a>
  </div>
</div>
{% endblock %}

templates/post/post_list.html
{% extends 'base.html' %} {% block content %} {% load static %}
<div>
  <h2>Post page</h2>

  <a href="{% url 'post:create' %}">Create a post</a>

  <div>
    {% if object_list %}
    <p>This are the post</p>
    <div>
      {% for obj in object_list %}
      <div>
        {% if obj.image %}
        <img
          style="width: 200px; display: flex; float: right;"
          src="{{ obj.image.url }}"
        />
        <br clear="all" />
        {% endif %}
        <h3><a href="{% url 'post:detail' obj.id%}">{{obj.title }}</a></h3>
        <p>{{obj.body }}</p>
        <p>It has {{obj.like.liker.all|length}} likes</p>
        <p>{{obj.comment.all|length}} comment</p>
        {% if request.user.is_authenticated %}
        <div style="display:inline-flex ;">
          <form action="{% url 'post:like' %}" method="POST">
            {% csrf_token %}
            <input type="submit" value="like" />
            <input type="hidden" name="post_id" value="{{obj.id}}" />
          </form>

          <form action="{% url 'post:unlike' %}" method="POST">
            {% csrf_token %}
            <input type="submit" value="unlike" />
            <input type="hidden" name="post_id" value="{{obj.id}}" />
          </form>
        </div>
        {% endif %}
      </div>
      <hr />
      {% endfor %}
    </div>
    {% endif %}
  </div>
</div>
{% endblock %}